earldouglas/sbt-war

README.md

Hi, I hope the addition is to your liking. Thanks, Jan

changed README to include JRebel

---

README.md

Update JRebel integration instructions

---

README.md

Add documentation on configuring Jetty logging

---

src/main/scala/container.scala

Rename some task keys to less conflicty values

---

docs/2.0.md
notes/2.0.2.markdown
src/main/scala/com/earldouglas/xwp/WarPlugin.scala

Add the .war file to what gets published

---

docs/2.0.md
src/sbt-test/container/jetty-7/build.sbt
src/sbt-test/container/jetty-8/build.sbt
src/sbt-test/container/jetty-9/build.sbt
src/sbt-test/container/tomcat-7/build.sbt

Add missing configurations

---

docs/2.0.md
src/main/scala/com/earldouglas/xwp/WarPlugin.scala

Publish the war package as the war package

---

docs/2.0.md
notes/2.0.4.markdown
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/main/scala/com/earldouglas/xwp/WarPlugin.scala
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala
src/sbt-test/container/multi-module-single-webapp/test

Discovered by http://stackoverflow.com/questions/31683637

Don't auto-trigger any of the plugins

---

docs/2.0.md
notes/2.0.5.markdown
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala

Add <container>:join to block sbt on running container

---

src/main/scala/com/earldouglas/xwp/WebappPlugin.scala

Cache library deps and project artifacts

---

docs/2.1.md
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala
src/sbt-test/webapp/changes/build.sbt
src/sbt-test/webapp/changes/changes/index.html
src/sbt-test/webapp/changes/project/plugins.sbt
src/sbt-test/webapp/changes/test

Work in progress.  See [open PRs against the *v2.1* branch][1].
[1]: https://github.com/earldouglas/xsbt-web-plugin/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+base%3Av2.1

Release v2.1

---

docs/2.1.md

See https://github.com/earldouglas/xsbt-web-plugin/issues/292#issuecomment-161341095

Show how to spread webapp resources around

---

docs/2.1.md

Add section on containerArgs

---

docs/2.1.md

In addition to Eclipse, describe how to setup debugging in IntelliJ IDEA.  Also include the sbt command to run Tomcat in debug mode.

Update debug documentation

---

docs/2.1.md

This includes @atais's changes to enable development mode for static resources.

Release version 2.1.1

---

src/main/scala/com/earldouglas/xwp/WarPlugin.scala
src/sbt-test/war/inherit/build.sbt
src/sbt-test/war/inherit/find-in-manifest.sbt
src/sbt-test/war/inherit/project/plugins.sbt
src/sbt-test/war/inherit/src/main/scala/servlets.scala
src/sbt-test/war/inherit/src/main/webapp/WEB-INF/web.xml
src/sbt-test/war/inherit/src/main/webapp/index.html
src/sbt-test/war/inherit/src/main/webapp/styles/style.css
src/sbt-test/war/inherit/test

Add support for inheriting the .jar manifest

---

docs/2.1.md

Document configuration externalization

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala
src/sbt-test/container/quickstart/build.sbt
src/sbt-test/container/quickstart/http-get.sbt
src/sbt-test/container/quickstart/project/plugins.sbt
src/sbt-test/container/quickstart/src/main/scala/servlets.scala
src/sbt-test/container/quickstart/src/main/webapp/WEB-INF/web.xml
src/sbt-test/container/quickstart/src/main/webapp/index.html
src/sbt-test/container/quickstart/src/main/webapp/styles/style.css
src/sbt-test/container/quickstart/test

Add <container>:quickstart that skips webapp prep

---

README.md
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala

Add debugAddress setting, and use it in debugOptions

---

README.md
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/sbt-test/container/scale/build.sbt
src/sbt-test/container/scale/http-get.sbt
src/sbt-test/container/scale/project/plugins.sbt
src/sbt-test/container/scale/src/main/scala/servlets.scala
src/sbt-test/container/scale/src/main/webapp/WEB-INF/web.xml
src/sbt-test/container/scale/src/main/webapp/index.html
src/sbt-test/container/scale/src/main/webapp/styles/style.css
src/sbt-test/container/scale/test

Add support for launching multiple containers

---

README.md
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/sbt-test/container/custom-runner/build.sbt
src/sbt-test/container/scale/build.sbt
src/sbt-test/container/scale/http-get.sbt
src/sbt-test/container/scale/project/plugins.sbt
src/sbt-test/container/scale/src/main/scala/servlets.scala
src/sbt-test/container/scale/src/main/webapp/WEB-INF/web.xml
src/sbt-test/container/scale/src/main/webapp/index.html
src/sbt-test/container/scale/src/main/webapp/styles/style.css
src/sbt-test/container/scale/test

Convert `containerLaunchCmd` to a port-dependent function

---

README.md
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/sbt-test/container/custom-runner/build.sbt

Make `containerLaunchCmd` dependent on the context path

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/sbt-test/container/scale/test

Allow `:debug` to be used with `containerScale`

---

README.md
build.sbt
project/build.sbt
src/sbt-test/webapp/unmanaged-resources/build.sbt
src/sbt-test/webapp/unmanaged-sources/build.sbt

http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html

fix deprecation warnings

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala

Allow for milestone versions of sbt

---

.travis.yml
build.sbt
project/build.properties
src/main/scala-sbt-0.13/com/earldouglas/xwp/Compat.scala
src/main/scala-sbt-1.0/com/earldouglas/xwp/Compat.scala
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/main/scala/com/earldouglas/xwp/HerokuDeploy.scala
src/main/scala/com/earldouglas/xwp/WarPlugin.scala
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala
src/sbt-test/container/fork-options/build.sbt
src/sbt-test/war/inherit/build.sbt
src/sbt-test/war/simple/build.sbt

fix https://github.com/earldouglas/xsbt-web-plugin/issues/166

support sbt 1.0

---

src/main/scala-sbt-1.0/com/earldouglas/xwp/Compat.scala

Fix source filters in sbt 1.0 watchSourceSetting

---

docs/examples/payara-micro/README.md
docs/examples/payara-micro/build.sbt
docs/examples/payara-micro/project/build.properties
docs/examples/payara-micro/project/plugins.sbt
docs/examples/payara-micro/src/main/scala/local/test/Main.scala
docs/examples/payara-micro/src/main/scala/local/test/endpoint/Hello.scala
docs/examples/payara-micro/src/main/webapp/WEB-INF/web.xml

Add an example using the Payara Micro container

---

.github/workflows/scala.yml
build.sbt
src/sbt-test/container/combined/project/plugins.sbt
src/sbt-test/container/custom-runner/project/plugins.sbt
src/sbt-test/container/multi-module-multi-webapp/project/plugins.sbt
src/sbt-test/container/multi-module-single-webapp/project/plugins.sbt
src/sbt-test/container/test/build.sbt
src/sbt-test/container/test/project/plugins.sbt
src/sbt-test/war/combined/project/plugins.sbt
src/sbt-test/webapp/combined/project/plugins.sbt

* Drop the `plugin.version` configuration option
* Test under all cross-sbt versions in CI

Bring the build up to date

---

docs/2.2.x.md
docs/2.3.x.md
docs/3.0.x.md
docs/4.1.x.md
docs/4.2.x.md

This is a follow-up to 66ac63b, updating the docs accordingly.

Rename plugins config files to plugins.sbt in docs

---

CONTRIBUTING.md

This tracks the publishing process that was just used for 4.2.3, and
sets up a checklist for next time.

Add developer documentation

---

examples/http4s/build.sbt

Use a common version for http4s modules

---

examples/http4s/build.sbt

This reverts commit bf8ea187dfbe2f6cabe2f9452031e33ff1205272.

Revert "http4s-servlet: 0.21.34 -> 0.23.13 (#732)"

---

.github/workflows/examples-jetty-11.yml
examples/jetty-11/README.md
examples/jetty-11/build.sbt
examples/jetty-11/project/build.properties
examples/jetty-11/project/plugins.sbt
examples/jetty-11/shell.nix
examples/jetty-11/src/main/scala/GettingStartedServlet.scala
examples/jetty-11/src/main/webapp/WEB-INF/web.xml
examples/jetty-11/src/test/scala/Http.scala
examples/jetty-11/src/test/scala/TestSuite.scala

Add example: Jetty 11

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.6` to `6.2023.7`

payara-micro: 6.2023.6 -> 6.2023.7

---

build.sbt

📦 Updates 
from `1.12.512` to `1.12.523`

aws-java-sdk: 1.12.512 -> 1.12.523

---

build.sbt

📦 Updates 
from `1.12.523` to `1.12.528`

aws-java-sdk: 1.12.523 -> 1.12.528

---

build.sbt

📦 Updates 
from `1.12.528` to `1.12.533`

aws-java-sdk: 1.12.528 -> 1.12.533

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.7` to `6.2023.8`

payara-micro: 6.2023.7 -> 6.2023.8

---

build.sbt

📦 Updates 
from `1.12.533` to `1.12.538`

aws-java-sdk: 1.12.533 -> 1.12.538

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.15` to `2.0.16`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.16) - [Version Diff](https://github.com/zio/zio/compare/v2.0.15...v2.0.16)

zio: 2.0.15 -> 2.0.16

---

examples/adder/build.sbt
examples/zio/build.sbt

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.2.220` to `2.2.222`

h2: 2.2.220 -> 2.2.222

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.16` to `2.0.17`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.17) - [Version Diff](https://github.com/zio/zio/compare/v2.0.16...v2.0.17)

zio: 2.0.16 -> 2.0.17

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.8` to `6.2023.9`

payara-micro: 6.2023.8 -> 6.2023.9

---

examples/adder/build.sbt
examples/zio/build.sbt

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.2.222` to `2.2.224`

h2: 2.2.222 -> 2.2.224

---

build.sbt

📦 Updates 
from `1.12.565` to `1.12.566`

aws-java-sdk: 1.12.565 -> 1.12.566

---

build.sbt

📦 Updates 
from `1.12.566` to `1.12.571`

aws-java-sdk: 1.12.566 -> 1.12.571

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.9` to `6.2023.10`

payara-micro: 6.2023.9 -> 6.2023.10

---

build.sbt

📦 Updates 
from `1.12.571` to `1.12.576`

aws-java-sdk: 1.12.571 -> 1.12.576

---

build.sbt

📦 Updates 
from `1.12.576` to `1.12.581`

aws-java-sdk: 1.12.576 -> 1.12.581

---

build.sbt

📦 Updates 
from `1.12.581` to `1.12.587`

aws-java-sdk: 1.12.581 -> 1.12.587

---

build.sbt

📦 Updates 
from `1.12.587` to `1.12.592`

aws-java-sdk: 1.12.587 -> 1.12.592

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.10` to `6.2023.11`

payara-micro: 6.2023.10 -> 6.2023.11

---

build.sbt

📦 Updates 
from `1.12.604` to `1.12.609`

aws-java-sdk: 1.12.604 -> 1.12.609

---

build.sbt

📦 Updates 
from `1.12.609` to `1.12.620`

aws-java-sdk: 1.12.609 -> 1.12.620

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.19` to `2.0.20`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.20) - [Version Diff](https://github.com/zio/zio/compare/v2.0.19...v2.0.20)

zio: 2.0.19 -> 2.0.20

---

build.sbt

📦 Updates 
from `1.12.620` to `1.12.629`

aws-java-sdk: 1.12.620 -> 1.12.629

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.11` to `6.2023.12`

payara-micro: 6.2023.11 -> 6.2023.12

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2023.12` to `6.2024.1`

payara-micro: 6.2023.12 -> 6.2024.1

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.1` to `6.2024.2`

payara-micro: 6.2024.1 -> 6.2024.2

---

examples/free/build.sbt

📦 Updates org.typelevel:kind-projector from `0.13.2` to `0.13.3`

kind-projector: 0.13.2 -> 0.13.3

---

build.sbt

📦 Updates 
from `1.12.666` to `1.12.676`

aws-java-sdk: 1.12.666 -> 1.12.676

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.2` to `6.2024.3`

payara-micro: 6.2024.2 -> 6.2024.3

---

build.sbt

📦 Updates 
from `1.12.676` to `1.12.681`

aws-java-sdk: 1.12.676 -> 1.12.681

---

build.sbt

📦 Updates 
from `1.12.681` to `1.12.686`

aws-java-sdk: 1.12.681 -> 1.12.686

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.3` to `6.2024.5`

payara-micro: 6.2024.3 -> 6.2024.5

---

build.sbt

📦 Updates 
from `1.12.696` to `1.12.734`

aws-java-sdk: 1.12.696 -> 1.12.734

---

build.sbt

📦 Updates 
from `1.12.734` to `1.12.739`

aws-java-sdk: 1.12.734 -> 1.12.739

---

build.sbt

📦 Updates 
from `1.12.739` to `1.12.748`

aws-java-sdk-elasticbeanstalk, ...: 1.12.739 -> 1.12.748

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.5` to `6.2024.6`

payara-micro: 6.2024.5 -> 6.2024.6

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.2` to `2.1.4`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/2.1.4) - [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.4) - [Version Diff](https://github.com/zio/zio/compare/v2.1.2...v2.1.4)

zio: 2.1.2 -> 2.1.4

---

build.sbt

📦 Updates 
from `1.12.748` to `1.12.753`

aws-java-sdk: 1.12.748 -> 1.12.753

---

build.sbt

📦 Updates 
from `1.12.753` to `1.12.757`

aws-java-sdk: 1.12.753 -> 1.12.757

---

examples/mustache/build.sbt

📦 Updates 
* com.github.spullara.mustache.java:compiler
* com.github.spullara.mustache.java:scala-extensions-2.12
from `0.9.13` to `0.9.14`

mustache.java: 0.9.13 -> 0.9.14

---

.github/workflows/examples-adder.yml
examples/adder/build.sbt
examples/zio/build.sbt

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.2.224` to `2.3.230`

h2: 2.2.224 -> 2.3.230

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.6` to `6.2024.7`

payara-micro: 6.2024.6 -> 6.2024.7

---

examples/sbt-1.x/project/build.properties
project/build.properties

📦 Updates 
* [org.scala-sbt:sbt](https://github.com/sbt/sbt)
* [org.scala-sbt:scripted-plugin](https://github.com/sbt/sbt)
from `1.10.0` to `1.10.1`
📜 [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.10.1) - [Version Diff](https://github.com/sbt/sbt/compare/v1.10.0...v1.10.1)

sbt, scripted-plugin: 1.10.0 -> 1.10.1

---

build.sbt

📦 Updates 
from `1.12.762` to `1.12.765`

aws-java-sdk: 1.12.762 -> 1.12.765

---

build.sbt

📦 Updates 
from `1.12.765` to `1.12.767`

aws-java-sdk-elasticbeanstalk, ...: 1.12.765 -> 1.12.767

---

build.sbt

📦 Updates 
from `1.12.767` to `1.12.770`

aws-java-sdk: 1.12.767 -> 1.12.770

---

examples/adder/build.sbt
examples/zio/build.sbt

📦 Updates [com.h2database:h2](https://github.com/h2database/h2database) from `2.3.230` to `2.3.232`

h2: 2.3.230 -> 2.3.232

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.7` to `6.2024.8`

payara-micro: 6.2024.7 -> 6.2024.8

---

build.sbt

📦 Updates 
from `1.12.770` to `1.12.771`

aws-java-sdk: 1.12.770 -> 1.12.771

---

build.sbt

📦 Updates 
from `1.12.771` to `1.12.772`

aws-java-sdk: 1.12.771 -> 1.12.772

---

examples/payara-micro/build.sbt

📦 Updates [fish.payara.extras:payara-micro](https://github.com/payara/Payara) from `6.2024.8` to `6.2024.9`

payara-micro: 6.2024.8 -> 6.2024.9

---

src/main/scala/com/earldouglas/sbt/war/WarPackageRunnerPlugin.scala
src/sbt-test/sbt-war/combined/scenarios/war-runner-plugin.sbt
src/sbt-test/sbt-war/combined/test

WarPackageRunnerPlugin: init

---

src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunner.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala
src/sbt-test/sbt-war/combined/scenarios/webapp-components-runner-plugin.sbt
src/sbt-test/sbt-war/combined/test
src/test/fakeproject/src/main/webapp/bar.html
src/test/fakeproject/src/main/webapp/baz/raz.css
src/test/fakeproject/src/main/webapp/foo.html
src/test/scala/com/earldouglas/sbt/war/HttpClient.scala
src/test/scala/com/earldouglas/sbt/war/WebappComponentsRunnerTest.scala

WebappComponentsRunner[Plugin]: init

---

src/main/scala/com/earldouglas/sbt/war/RunnerKeysPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WarPackageRunnerPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala
src/sbt-test/plugins/everything/sbt/test.sbt
src/sbt-test/plugins/everything/template.sbt
src/sbt-test/plugins/everything/test
src/sbt-test/plugins/webapp-components-runner/sbt/test.sbt
src/sbt-test/plugins/webapp-components-runner/test

* Collect shared runner keys
* Add an `everything` test with both runners

Move runner settings under configuration

---

src/main/scala/com/earldouglas/sbt/war/SbtWar.scala
src/main/scala/com/earldouglas/sbt/war/WarPackagePlugin.scala
src/main/scala/com/earldouglas/sbt/war/WarPackageRunnerPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappRunnerPlugin.scala
src/sbt-test/plugins/sbt-war/project/build.properties
src/sbt-test/plugins/war-package/sbt/test.sbt
src/sbt-test/plugins/webapp-components/sbt/test.sbt
src/template/build.sbt
src/template/src/main/resources/logback.xml
src/template/src/main/scala/04-runners/servlet.scala

* Copy edit comments
* Add non-compiled classpath resources to the scripted tests
* Move `War / forkOptions` out of config to `warForkOptions`
* Add some missing type annotations
* Re-scope some settings helpers

Misc cleanup for usability

---

src/sbt-test/plugins/war-package/sbt/test.sbt
src/sbt-test/plugins/war-package/test

Add a scripted test to check the .war manifest

---

build.sbt
src/main/scala/com/earldouglas/sbt/war/SbtWar.scala

Refactor startWar to use WarRunner from war-runner

---

README.md

Document a typical project and .war file structure

---

README.md

Add docs on triggered execution and container logs

---

README.md
src/main/scala/com/earldouglas/sbt/war/SbtWar.scala

Use sbt.Keys.forkOptions as the default fork options

---

README.md

sbt-war: 5.0.0-M9 -> 5.0.0

---

src/main/scala/com/earldouglas/sbt/war/SbtWar.scala

Block on stopping the server until the process exits

---

build.sbt
devenv.nix
src/main/scala-2.12/com/earldouglas/sbt/war/Compat.scala
src/main/scala-3/com/earldouglas/sbt/war/Compat.scala
src/main/scala/com/earldouglas/sbt/war/SbtWar.scala
src/main/scala/com/earldouglas/sbt/war/WarPackagePlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponents.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsPlugin.scala
src/sbt-test/sbt-war/test-war-start/test
src/sbt-test/war-package/manifest/sbt/test-1.x.sbt
src/sbt-test/war-package/manifest/sbt/test-2.x.sbt
src/sbt-test/war-package/manifest/sbt/test.sbt
src/sbt-test/war-package/manifest/template.sbt
src/sbt-test/war-package/manifest/test
src/sbt-test/war-package/package/sbt/test-1.x.sbt
src/sbt-test/war-package/package/sbt/test-2.x.sbt
src/sbt-test/war-package/package/sbt/test.sbt
src/sbt-test/war-package/package/template.sbt

Cross-build for sbt 2.0.0-RC4
