earldouglas/sbt-war

src/main/scala/container.scala

Fixes #202
This is a hacktastic way to silence some benign error output caused
by sbt when destroying a forked process.  The output appears to
come from ProcessImpl[1].
1. https://github.com/sbt/sbt/blob/v0.13.7/util/process/src/main/scala/sbt/ProcessImpl.scala#L101

Suppress sbt's stderr when waiting for exit

---

src/main/scala/plugin.scala
src/main/scala/webapp.scala

* Use the container's name field by reference
* Drop unnecessary self: Plugin type

A bit o' housekeeping

---

src/main/scala/plugin.scala
src/sbt-test/xwp/auto-jetty-port-9090/build.sbt
src/sbt-test/xwp/auto-jetty-port-9090/find-in-zip.sbt
src/sbt-test/xwp/auto-jetty-port-9090/http-get.sbt
src/sbt-test/xwp/auto-jetty-port-9090/project/plugins.sbt
src/sbt-test/xwp/auto-jetty-port-9090/src/main/scala/servlets.scala
src/sbt-test/xwp/auto-jetty-port-9090/src/main/webapp/WEB-INF/web.xml
src/sbt-test/xwp/auto-jetty-port-9090/src/main/webapp/index.html
src/sbt-test/xwp/auto-jetty-port-9090/src/main/webapp/styles/style.css
src/sbt-test/xwp/auto-jetty-port-9090/test
src/sbt-test/xwp/auto-jetty/build.sbt
src/sbt-test/xwp/auto-jetty/find-in-zip.sbt
src/sbt-test/xwp/auto-jetty/http-get.sbt
src/sbt-test/xwp/auto-jetty/project/plugins.sbt
src/sbt-test/xwp/auto-jetty/src/main/scala/servlets.scala
src/sbt-test/xwp/auto-jetty/src/main/webapp/WEB-INF/web.xml
src/sbt-test/xwp/auto-jetty/src/main/webapp/index.html
src/sbt-test/xwp/auto-jetty/src/main/webapp/styles/style.css
src/sbt-test/xwp/auto-jetty/test

Fixes #168
Fixes #204
This adds an initial version of an AutoPlugin for configuring a Jetty
container.  It includes support for the same options currently
available via arguments to `jetty()`, but now as individual sbt
settings.
**TODO:**

Add a prototype AutoPlugin implementation

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala

I currently use a embedded tomcat container that supports accepting the webapp's dependency classpath as a argument, then mounts those entries in that classpath in the webapp using tomcat's resource API. While upgrading to xsbt-web-plugin 2.0, changing launchCmd from a task to setting prevents me from being able to pass the dependency classpath as argument in my project because settings cannot depend on tasks in SBT.

Launcher cmd task

---

build.sbt
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala

Continuation of issue https://github.com/earldouglas/xsbt-web-plugin/issues/298
To enable development mode:
``` scala
...
target in webappPrepare := (sourceDirectory in Compile).value / "webapp",
watchSources := watchSources.value.filterNot { x =>
x.isDirectory || x.getAbsolutePath.contains("webapp")
}
```

Serving static resource directly in from sourceDirectory

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala

xsbt-web-plugin uses sbt APIs from 0.13.6 (`AutoPlugin`,
`enablePlubins`, etc.).
This change will cause xsbt-web-plugin to throw an exception if it is
used with an incompatible version of sbt.
Fixes #303

Throw an exception if sbt version is < 0.13.6

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/sbt-test/container/debug/build.sbt
src/sbt-test/container/debug/http-get.sbt
src/sbt-test/container/debug/project/plugins.sbt
src/sbt-test/container/debug/src/main/scala/servlets.scala
src/sbt-test/container/debug/src/main/webapp/WEB-INF/web.xml
src/sbt-test/container/debug/src/main/webapp/index.html
src/sbt-test/container/debug/src/main/webapp/styles/style.css
src/sbt-test/container/debug/test

This adds `tomcat:debug` and `jetty:debug`, which launch the container
with the arguments set in `debugOptions`, which defaults to:
```scala
Seq(
"-Xdebug"
, "-Xrunjdwp:transport=dt_socket,address=8888,server=y,suspend=n"
)
```
Relevant docs:
* https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/introclientissues005.html
* http://docs.oracle.com/javase/1.5.0/docs/guide/jpda/conninv.html
Fixes #301

Add a `debug` container command

---

docs/2.2.md

- https://github.com/sbt/sbt/blob/v0.13.13/main/src/main/scala/sbt/Defaults.scala#L2030-L2031
- https://github.com/sbt/sbt/commit/61509408c9bbc0581bb5c41c0b69c19402cb1fb8

sbt.BuildExtra#seq is deprecated

---

src/sbt-test/container/multi-module-multi-webapp/build.sbt
src/sbt-test/container/multi-module-single-webapp/build.sbt
src/sbt-test/war/inherit/build.sbt
src/sbt-test/war/simple/build.sbt
src/sbt-test/war/simple/test
src/sbt-test/webapp/unmanaged-resources/build.sbt
src/sbt-test/webapp/unmanaged-sources/build.sbt
src/sbt-test/webapp/web-inf-lib/build.sbt
src/sbt-test/webapp/webapp-dest/build.sbt
src/sbt-test/webapp/webapp-src/build.sbt

This is prepare for sbt 1.0 cross build because default scalaVersion is 2.12 since sbt 1.0.

specify scalaVersion in scripted tests

---

src/main/scala/com/earldouglas/xwp/JettyPlugin.scala

Without this, users will encounter an error about `module-info.class` when using jars compiled on JDK9.
See https://github.com/eclipse/jetty.project/issues/1692 for more information
Fixes #361 
Once merged, https://github.com/scalatra/sbt-scalatra/issues/55 could be addressed.

Updates jetty-runner to 9.4.8.v20171121

---

src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala
src/sbt-test/webapp/combined/test

This adds a new `webappPrepareQuick` task used by `quickstart` to copy
webapp sources from `sourceDirectory in webappPrepare` to
`target/webapp-quick`, and then run `webappPostProcess` on it.
The two target directories `target/webapp-quick` and `target/webapp` are
kept separate so that artifacts from `quickstart` and `start` don't
interfere with each other.
Fixes #373

Add support for webappPostProcess to quickstart

---

.github/workflows/scala.yml

This changes the GitHub Actions configuration to enable builds for pull
requests, so that PRs from forked repos trigger CI builds.
See [configuring workflow events][1] in the GitHub docs for details on
build triggers.
[1]: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#configuring-workflow-events

Add pull request trigger for CI build

---

src/sbt-test/examples/scala-js/build.sbt
src/sbt-test/war/combined/build.sbt
src/sbt-test/webapp/combined/build.sbt

sbt 1.4.x no longer uses the source directory name for scripted test
project names, which are in turn used for path-based verification of
artifacts by the following scripted tests:
* `examples/scala-js`
* `war/combined`
* `webapp/combined`
This change sets project names for these, allowing #423 to be merged.

Set project names for some scripted tests

---

src/main/scala/com/earldouglas/xwp/WebappPlugin.scala
src/sbt-test/webapp/combined/test

This modifies the `cacheify` function to include not just new and
modified files, but missing target files as well.  With this change,
external deletion/modification of target files will be recreated from
source by `webappPrepare` and `webappPrepareQuick`.
Fixes #376

Check for missing files in cache

---

.github/workflows/scala.yml
src/sbt-test/reqs/min/build.sbt

Since the current version of sbt [is not keen][1] to run scripted tests
using sbt 0.13.6, we need to manually run it after `sbt scripted` skips
it.
This changes the GitHub Actions configuration to manually run 
`sbt jetty:test` under *reqs/min* after the rest of the scripted tests
pass.
Fixes #437
[1]: https://github.com/earldouglas/xsbt-web-plugin/runs/1907163904?check_suite_focus=true#step:6:42

Add a CI step to manually test reqs/min

---

src/main/scala-sbt-0.13/com/earldouglas/xwp/Compat.scala
src/main/scala-sbt-1.0/com/earldouglas/xwp/Compat.scala
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala

This uses `Compat` for delegation to the different sbt APIs, and fixes
the compile-time error message:
```
[warn] WebappPlugin.scala:175:25: method jar in object IO is deprecated (since 1.3.2): Please specify whether to use a static timestamp
[warn]         _          = IO.jar(files, webappLibDir / jarFile, new Manifest)
[warn]                         ^
```
Fixes #441

Update to the non-deprecated `IO#jar`

---

src/sbt-test/examples/payara-micro/build.sbt

This updates the Payara Micro test to use the webapp path provided as an
argument to `containerLaunchCmd`.  The value of `path` is an absolute
path to either *target/webapp* or *target/webapp-quick*, depending on
whether `container:test` or `container:quicktest` is used.
This is largely a noop as `container:quicktest` fails, possibly because
Payara Micro uses a separate classloader for the webapp than for the
forked JVM.

Use the webapp path provided to containerLaunchCmd

---

src/reqs/build.sbt
src/reqs/src/main/scala/GettingStartedServlet.scala
src/reqs/src/test/scala/TestSuite.scala

A given version of ScalaTest isn't always available across different
versions of Scala.  This replaces it with JUnit, which is independent of
the Scala (or sbt) version.  Since the test case is so simple for reqs
checks, we can get away with just using JUnit.

Switch from ScalaTest to JUnit for portability

---

src/reqs/check.sh

This updates reqs check to use temp directories for all artifacts, so
that it won't pollute your local copy of the source tree:
* Downloaded sbt launcher *.jar* files
* Build configuration
* Build artifacts

Keep the source tree clean using tmp dirs

---

src/reqs/check.sh

This expands reqs support checks across combinations of ranges of sbt
and Scala.
* sbt: 0.13.6 - 1.5.2
* Scala: 2.10.2 - 3.0.0

Expand reqs check across sbt and scala ranges

---

README.md
src/main/scala/com/earldouglas/xwp/TomcatPlugin.scala
src/sbt-test/container/combined/test

This also adds tests for webapp-runner 7.0.91.0, 8.0.52.0, and 8.5.61.0.
See https://repo1.maven.org/maven2/com/heroku/webapp-runner/

Update default webapp-runner to 9.0.41.0

---

README.md

This updates the "starting from scratch" section of the readme with an
example that uses the [`@WebServlet`][1] annotation, removing the need
for a *web.xml* file.
[1]: https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/WebServlet.html

Update the quick start guide to use @WebServlet

---

.github/workflows/build.yml
.scalafmt.conf
project/plugins.sbt
src/main/scala-sbt-1.0/com/earldouglas/xwp/Compat.scala
src/main/scala/com/earldouglas/xwp/ContainerPlugin.scala
src/main/scala/com/earldouglas/xwp/ElasticBeanstalkDeploy.scala
src/main/scala/com/earldouglas/xwp/HerokuDeploy.scala
src/main/scala/com/earldouglas/xwp/JettyPlugin.scala
src/main/scala/com/earldouglas/xwp/TomcatPlugin.scala
src/main/scala/com/earldouglas/xwp/WarPlugin.scala
src/main/scala/com/earldouglas/xwp/WebappPlugin.scala

This adds Scalafmt, applies it to the source code, and adds a build-time
check in CI.  Scalafmt doesn't technically support Scala 2.12.11:
```
[info] Checking 8 Scala sources...
[error] Invalid version: 2.12.11: xsbt-web-plugin/.scalafmt.conf
[error] Invalid version: 2.12.11: xsbt-web-plugin/.scalafmt.conf
[error] (Compile / scalafmtCheck) Invalid version: 2.12.11: xsbt-web-plugin/.scalafmt.conf
[error] (Test / scalafmtCheck) Invalid version: 2.12.11: xsbt-web-plugin/.scalafmt.conf
```
But it doesn't complain if we don't tell it what version we're on.
See https://scalameta.org/scalafmt/docs/installation.html#sbt

Standardize formatting with Scalafmt

---

README.md
src/main/scala/com/earldouglas/xwp/JettyPlugin.scala
src/sbt-test/container/combined/test

This also updates the `container/combined` test to use jetty-runner
9.4.42.
See https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/
We can't use versions 10 or 11 yet because they're both built with JDK
11, while we're still on JDK 8:
* https://github.com/eclipse/jetty.project/blob/jetty-9.4.43.v20210624/pom.xml#L163
* https://github.com/eclipse/jetty.project/blob/jetty-10.0.0/pom.xml#L166

Update default jetty-runner to 9.4.42

---

src/reqs/check.sh

With Bintray [shutting down][1], the servers simply return `Forbidden!`
when trying to retrieve *sbt-launch.jar*.  This switches to Typesafe's
repo instead.
[1]: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Don't use Bintray to retrieve sbt-launch.jar

---

src/main/scala/com/earldouglas/xwp/HerokuDeploy.scala

This causes sbt to return an error status when `herokuDeploy` fails, as
detected by a non-zero exit code from the forked process.  This helps
flag CI if something goes wrong during deployment.
Fixes #465

Throw an error on non-zero exit from HerokuDeploy

---

build.sbt

This prevents sbt from complaining about the `crossSbtVersions` key
not being used by any other settings/tasks:
```
[warn] there's a key that's not used by any other settings/tasks:
[warn]
[warn] * xsbt-web-plugin / crossSbtVersions
[warn]   +- build.sbt:2
[warn]
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
```

Add crossSbtVersions to excludeLintKeys

---

.scalafmt.conf
project/plugins.sbt

Also add `version` and `runner.dialect`, which are now required, to the
Scalafmt config.

Update sbt-scalafmt to 2.4.4

---

build.sbt

📦 Updates 
from `1.12.504` to `1.12.506`

aws-java-sdk: 1.12.504 -> 1.12.506

---

.scalafmt.conf

📦 Updates [org.scalameta:scalafmt-core](https://github.com/scalameta/scalafmt) from `3.7.7` to `3.7.9`
📜 [GitHub Release Notes](https://github.com/scalameta/scalafmt/releases/tag/v3.7.9) - [Version Diff](https://github.com/scalameta/scalafmt/compare/v3.7.7...v3.7.9)

scalafmt-core: 3.7.7 -> 3.7.9

---

build.sbt

📦 Updates 
from `1.12.506` to `1.12.512`

aws-java-sdk: 1.12.506 -> 1.12.512

---

build.sbt

📦 Updates 
from `1.12.538` to `1.12.543`

aws-java-sdk: 1.12.538 -> 1.12.543

---

build.sbt

📦 Updates 
from `1.12.543` to `1.12.547`

aws-java-sdk: 1.12.543 -> 1.12.547

---

examples/async/build.sbt
examples/getting-started/build.sbt
examples/http4s/build.sbt
examples/jetty-11/build.sbt
examples/scalatra/build.sbt
src/sbt-test/jetty-plugin/default/build.sbt
src/sbt-test/scala/2/build.sbt
src/sbt-test/tomcat-plugin/default/build.sbt

📦 Updates [org.scalatest:scalatest](https://github.com/scalatest/scalatest) from `3.2.16` to `3.2.17`

scalatest: 3.2.16 -> 3.2.17

---

build.sbt

📦 Updates 
from `1.12.547` to `1.12.552`

aws-java-sdk: 1.12.547 -> 1.12.552

---

examples/free/build.sbt

📦 Updates [org.scala-lang:scala-library](https://github.com/scala/scala) from `2.13.11` to `2.13.12`
📜 [GitHub Release Notes](https://github.com/scala/scala/releases/tag/v2.13.12) - [Version Diff](https://github.com/scala/scala/compare/v2.13.11...v2.13.12)

scala-library: 2.13.11 -> 2.13.12

---

build.sbt

📦 Updates 
from `1.12.552` to `1.12.556`

aws-java-sdk: 1.12.552 -> 1.12.556

---

examples/scala-js/scala-js.sbt

📦 Updates [org.scala-js:scalajs-dom](https://github.com/scala-js/scala-js-dom) from `2.6.0` to `2.7.0`
📜 [GitHub Release Notes](https://github.com/scala-js/scala-js-dom/releases/tag/v2.7.0) - [Version Diff](https://github.com/scala-js/scala-js-dom/compare/v2.6.0...v2.7.0)

scalajs-dom: 2.6.0 -> 2.7.0

---

build.sbt

📦 Updates 
from `1.12.556` to `1.12.560`

aws-java-sdk: 1.12.556 -> 1.12.560

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.17` to `2.0.18`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.18) - [Version Diff](https://github.com/zio/zio/compare/v2.0.17...v2.0.18)

zio: 2.0.17 -> 2.0.18

---

examples/scala-js/project/plugins.sbt

📦 Updates 
* [org.scala-js:sbt-scalajs](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-compiler](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-library](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-test-bridge](https://github.com/scala-js/scala-js)
from `1.13.2` to `1.14.0`
📜 [GitHub Release Notes](https://github.com/scala-js/scala-js/releases/tag/v1.14.0) - [Version Diff](https://github.com/scala-js/scala-js/compare/v1.13.2...v1.14.0)

sbt-scalajs: 1.13.2 -> 1.14.0

---

examples/scala-js/scala-js.sbt

📦 Updates [org.scala-js:scalajs-dom](https://github.com/scala-js/scala-js-dom) from `2.7.0` to `2.8.0`
📜 [GitHub Release Notes](https://github.com/scala-js/scala-js-dom/releases/tag/v2.8.0) - [Version Diff](https://github.com/scala-js/scala-js-dom/compare/v2.7.0...v2.8.0)

scalajs-dom: 2.7.0 -> 2.8.0

---

build.sbt

📦 Updates 
from `1.12.560` to `1.12.565`

aws-java-sdk: 1.12.560 -> 1.12.565

---

examples/mustache/build.sbt

📦 Updates 
* com.github.spullara.mustache.java:compiler
* com.github.spullara.mustache.java:scala-extensions-2.12
from `0.9.10` to `0.9.11`

compiler, scala-extensions-2.12: 0.9.10 -> 0.9.11

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.18` to `2.0.19`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.19) - [Version Diff](https://github.com/zio/zio/compare/v2.0.18...v2.0.19)

zio: 2.0.18 -> 2.0.19

---

build.sbt

📦 Updates 
from `1.12.592` to `1.12.595`

aws-java-sdk: 1.12.592 -> 1.12.595

---

build.sbt

📦 Updates 
from `1.12.595` to `1.12.604`

aws-java-sdk: 1.12.595 -> 1.12.604

---

examples/scala-js/project/plugins.sbt

📦 Updates 
* [org.scala-js:sbt-scalajs](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-compiler](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-library](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-test-bridge](https://github.com/scala-js/scala-js)
from `1.14.0` to `1.15.0`
📜 [GitHub Release Notes](https://github.com/scala-js/scala-js/releases/tag/v1.15.0) - [Version Diff](https://github.com/scala-js/scala-js/compare/v1.14.0...v1.15.0)

sbt-scalajs: 1.14.0 -> 1.15.0

---

build.sbt

📦 Updates 
from `1.12.629` to `1.12.632`

aws-java-sdk: 1.12.629 -> 1.12.632

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.20` to `2.0.21`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.21) - [Version Diff](https://github.com/zio/zio/compare/v2.0.20...v2.0.21)

zio: 2.0.20 -> 2.0.21

---

build.sbt

📦 Updates 
from `1.12.632` to `1.12.636`

aws-java-sdk: 1.12.632 -> 1.12.636

---

build.sbt

📦 Updates 
from `1.12.636` to `1.12.641`

aws-java-sdk: 1.12.636 -> 1.12.641

---

build.sbt

📦 Updates 
from `1.12.641` to `1.12.646`

aws-java-sdk: 1.12.641 -> 1.12.646

---

build.sbt

📦 Updates 
from `1.12.646` to `1.12.651`

aws-java-sdk: 1.12.646 -> 1.12.651

---

build.sbt

📦 Updates 
from `1.12.651` to `1.12.656`

aws-java-sdk: 1.12.651 -> 1.12.656

---

examples/async/build.sbt
examples/getting-started/build.sbt
examples/http4s/build.sbt
examples/jetty-11/build.sbt
examples/scalatra/build.sbt
src/sbt-test/jetty-plugin/default/build.sbt
src/sbt-test/scala/2/build.sbt
src/sbt-test/tomcat-plugin/default/build.sbt

📦 Updates [org.scalatest:scalatest](https://github.com/scalatest/scalatest) from `3.2.17` to `3.2.18`
📜 [GitHub Release Notes](https://github.com/scalatest/scalatest/releases/tag/release-3.2.18) - [Version Diff](https://github.com/scalatest/scalatest/compare/release-3.2.17...release-3.2.18)

scalatest: 3.2.17 -> 3.2.18

---

build.sbt

📦 Updates 
from `1.12.656` to `1.12.661`

aws-java-sdk: 1.12.656 -> 1.12.661

---

examples/free/build.sbt

📦 Updates [org.scala-lang:scala-library](https://github.com/scala/scala) from `2.13.12` to `2.13.13`
📜 [GitHub Release Notes](https://github.com/scala/scala/releases/tag/v2.13.13) - [Version Diff](https://github.com/scala/scala/compare/v2.13.12...v2.13.13)

scala-library: 2.13.12 -> 2.13.13

---

examples/scala-js/project/plugins.sbt

📦 Updates 
* [org.scala-js:sbt-scalajs](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-compiler](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-library](https://github.com/scala-js/scala-js)
* [org.scala-js:scalajs-test-bridge](https://github.com/scala-js/scala-js)
from `1.15.0` to `1.16.0`
📜 [GitHub Release Notes](https://github.com/scala-js/scala-js/releases/tag/v1.16.0) - [Version Diff](https://github.com/scala-js/scala-js/compare/v1.15.0...v1.16.0)

sbt-scalajs: 1.15.0 -> 1.16.0

---

build.sbt

📦 Updates 
from `1.12.686` to `1.12.696`

aws-java-sdk: 1.12.686 -> 1.12.696

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.21` to `2.0.22`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.0.22) - [Version Diff](https://github.com/zio/zio/compare/v2.0.21...v2.0.22)

zio: 2.0.21 -> 2.0.22

---

examples/mustache/build.sbt

📦 Updates 
* com.github.spullara.mustache.java:compiler
* com.github.spullara.mustache.java:scala-extensions-2.12
from `0.9.11` to `0.9.13`

mustache.java: 0.9.11 -> 0.9.13

---

examples/free/build.sbt

📦 Updates [org.scala-lang:scala-library](https://github.com/scala/scala) from `2.13.13` to `2.13.14`
📜 [GitHub Release Notes](https://github.com/scala/scala/releases/tag/v2.13.14) - [Version Diff](https://github.com/scala/scala/compare/v2.13.13...v2.13.14)

scala-library: 2.13.13 -> 2.13.14

---

.github/workflows/examples-zio.yml
examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.0.22` to `2.1.2`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.2) - [Version Diff](https://github.com/zio/zio/compare/v2.0.22...v2.1.2)

zio: 2.0.22 -> 2.1.2

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.4` to `2.1.5`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.5) - [Version Diff](https://github.com/zio/zio/compare/v2.1.4...v2.1.5)

zio: 2.1.4 -> 2.1.5

---

src/main/scala/com/earldouglas/xwp/TomcatPlugin.scala

📦 Updates [com.heroku:webapp-runner](https://github.com/heroku/webapp-runner) from `9.0.68.0` to `9.0.68.1`
📜 [GitHub Release Notes](https://github.com/heroku/webapp-runner/releases/tag/v9.0.68.1) - [Version Diff](https://github.com/heroku/webapp-runner/compare/v9.0.68.0...v9.0.68.1)

webapp-runner: 9.0.68.0 -> 9.0.68.1

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.5` to `2.1.6`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.6) - [Version Diff](https://github.com/zio/zio/compare/v2.1.5...v2.1.6)

zio: 2.1.5 -> 2.1.6

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.6` to `2.1.7`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.7) - [Version Diff](https://github.com/zio/zio/compare/v2.1.6...v2.1.7)

zio: 2.1.6 -> 2.1.7

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.7` to `2.1.8`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.8) - [Version Diff](https://github.com/zio/zio/compare/v2.1.7...v2.1.8)

zio: 2.1.7 -> 2.1.8

---

examples/zio/build.sbt

📦 Updates [dev.zio:zio](https://github.com/zio/zio) from `2.1.8` to `2.1.9`
📜 [GitHub Release Notes](https://github.com/zio/zio/releases/tag/v2.1.9) - [Version Diff](https://github.com/zio/zio/compare/v2.1.8...v2.1.9)

zio: 2.1.8 -> 2.1.9

---

src/main/scala/com/earldouglas/sbt/war/WarPackageRunnerPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappRunnerPlugin.scala

This will make the setting reusable by WebappComponentsRunnerPlugin later.

webappRunnerVersion: extract to WebappRunnerPlugin

---

README.md
src/main/scala/com/earldouglas/sbt/war/WarPackageRunnerPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala

This reduces the noise caused when destroying the forked war/webapp processeses throws stream closure exceptions:
```
Exception in thread "Thread-4" java.io.IOException: Stream closed
at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:289)
at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
at scala.sys.process.BasicIO$.loop$1(BasicIO.scala:238)
at scala.sys.process.BasicIO$.transferFullyImpl(BasicIO.scala:246)
at scala.sys.process.BasicIO$.transferFully(BasicIO.scala:227)
at scala.sys.process.BasicIO$.$anonfun$toStdErr$1(BasicIO.scala:216)
at …
```

Use BufferedOutput for forked JVM output strategy

---

src/main/scala/com/earldouglas/sbt/war/WarPackageRunnerPlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsRunnerPlugin.scala

This creates two new hidden settings:
* `WarPackageRunnerPlugin/warMainClass`
* `WebappComponentsRunnerPlugin/webappComponentsRunnerMainClass`
These are used when forking new container processes to specify the main method of the forked JVM.
Note that for WarPackageRunnerPlugin, we dropped the `-jar` argument and converted to `-cp` so that we can specify the main class manually.  This also lets us use multiple libraries in the `War` configuration, if ever needed.

Extract the container main class names to settings

---

build.sbt

📦 Updates [com.heroku:webapp-runner](https://github.com/heroku/webapp-runner) from `10.1.28.0` to `10.1.31.0`
📜 [GitHub Release Notes](https://github.com/heroku/webapp-runner/releases/tag/v10.1.31.0) - [Version Diff](https://github.com/heroku/webapp-runner/compare/v10.1.28.0...v10.1.31.0)

webapp-runner: 10.1.28.0 -> 10.1.31.0

---

src/main/scala/com/earldouglas/sbt/war/SbtWar.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponents.scala

Fix file paths when running on Windows

---

build.sbt
src/main/scala/com/earldouglas/sbt/war/SbtWar.scala

This makes publishing to Sonatype snapshots possible.

Move Servlet spec in front of the version suffix

---

README.md
src/main/scala/com/earldouglas/sbt/war/SbtWar.scala
src/sbt-test/plugins/sbt-war/test

For better ergonomics, this makes the following changes:
* Rename `warStart` to `warStartPackage`
* Rename `warQuickstart` to `warStart`
Closes #1007

Make quickstart the default

---

src/main/scala/com/earldouglas/sbt/war/SbtWar.scala
src/main/scala/com/earldouglas/sbt/war/WarPackagePlugin.scala
src/main/scala/com/earldouglas/sbt/war/WebappComponentsPlugin.scala
src/sbt-test/plugins/sbt-war/sbt/test.sbt
src/sbt-test/plugins/sbt-war/test
src/sbt-test/plugins/webapp-components/sbt/test.sbt
src/template/src/test/scala/04-runners/servlet.scala

This allows different sets of classes and libraries to be used with different configurations:
```
> Runtime / warStart
> Test / warStart
```
When omitted, the `Runtime` configuration is used:
```
> warStart
```

Set warStart, warClasses, and warLib per configuration
